Use virtual files instead of physical files (#18)
* Fix exeution error

I think that you have an error
```
TypeError: Cannot set property 'apply' of undefined
```

* Use virtual files instead of physical files

* Update index.js

* Fix importation